import 'dart:ffi';
import 'package:getwidget/getwidget.dart';
import 'package:flutter/material.dart';
import 'package:fresco/main.dart';
import 'package:fresco/secondary_home_page.dart';
import 'package:fresco/result_page.dart';
import 'package:google_fonts/google_fonts.dart';

class newfaqs extends StatefulWidget {
  const newfaqs({super.key});

  @override
  State<newfaqs> createState() => _newfaqsState();
}

class _newfaqsState extends State<newfaqs> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('FAQs'),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.all(5.0),
          child: Column(
            children: [
              SizedBox(
                height: 10,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title: "What is AI art/images generator application?",
                content:
                    "Fresco is an AI art/images generator application that utilizes deep learning technology to generate unique and visually stunning images.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title: "How does the AI art/images generator work?",
                content:
                    "Fresco uses deep learning algorithms to analyze and synthesize large amounts of data to create unique and aesthetically pleasing images.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title: "What kind of art/images can be generated using AI?",
                content:
                    "Fresco can generate a wide variety of images, including abstract art, landscapes, portraits, and more.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title: "How long does it take to generate an image using AI?",
                content:
                    "The time taken to generate an image depends on the complexity of the image and the processing power of the device. However, most images can be generated in a matter of seconds.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title: "Is the AI-generated art/images unique?",
                content:
                    "Yes, the images generated by Fresco are unique and cannot be replicated exactly.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title: "Can the user customize the AI-generated art/images?",
                content:
                    "No, currently, the user cannot customize the generated images. However, users can adjust certain parameters such as color and style.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title:
                    "Is it possible to download and save the generated art/images?",
                content:
                    "Yes, users can download and save the generated images to their device.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title:
                    "Is the AI-generated art/images available for commercial use?",
                content:
                    "No, the generated images are for personal use only and cannot be used for commercial purposes without the necessary permissions.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title:
                    "Can the AI-generated art/images be shared on social media?",
                content:
                    "Yes, users can share the generated images on social media platforms.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title:
                    "Is there any limit to the number of images that can be generated using the AI art/images generator application?",
                content:
                    "No, there is no limit to the number of images that can be generated using Fresco.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title: "What is the accuracy of the AI-generated art/images?",
                content:
                    "The accuracy of the AI-generated art/images depends on the quality and quantity of the data used to train the AI model.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title: "How frequently is the AI model updated?",
                content:
                    "The AI model is regularly updated to improve the quality and diversity of the generated images.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title:
                    "How secure is the data that is used to generate the AI art/images?",
                content:
                    "The data used to generate the AI art/images is stored securely and is only used for the intended purpose.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title:
                    "Can the user provide feedback on the generated art/images?",
                content:
                    "Yes, users can provide feedback on the generated art/images, which helps to improve the quality of the AI model.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title: "Can the user customize the AI-generated art/images?",
                content:
                    "No, currently, the user cannot customize the generated images. However, users can adjust certain parameters such as color and style.",
              ),
              SizedBox(
                height: 5,
              ),
              GFAccordion(
                textStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
                title:
                    "What kind of support is available for users of the AI art/images generator application?",
                content:
                    "Users can access online documentation and FAQs for support. Additionally, they can contact the support team via email for any queries or issues.",
              ),
              SizedBox(
                height: 5,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
